import matplotlib.pyplot as plt
import numpy as np

plt.style.use('default')
fig, ax = plt.subplots(figsize=(8, 6), dpi=300)
fig.patch.set_facecolor('white')
ax.set_facecolor('white')

USSBlue = '#00205B'
USSGold = '#D4AF37'
Teal = '#008080'

# Parallelogram in R^2 generated by v1 and v2
v1 = np.array([3.0, 0.5])
v2 = np.array([1.0, 2.5])

# Draw vectors
ax.annotate('', xy=v1, xytext=(0, 0), arrowprops=dict(arrowstyle='->', color=USSBlue, lw=3))
ax.text(v1[0]+0.1, v1[1]-0.2, r'$v_1$', fontsize=12, color=USSBlue, fontweight='bold')

ax.annotate('', xy=v2, xytext=(0, 0), arrowprops=dict(arrowstyle='->', color=USSGold, lw=3))
ax.text(v2[0]-0.4, v2[1]+0.1, r'$v_2$', fontsize=12, color=USSGold, fontweight='bold')

# Parallelogram fill
area_pts = np.array([[0,0], v1, v1+v2, v2, [0,0]])
ax.fill(area_pts[:,0], area_pts[:,1], color=Teal, alpha=0.3, label=r'Area = $|\det(v_1, v_2)|$')

ax.axhline(0, color='gray', linestyle=':', alpha=0.6)
ax.axvline(0, color='gray', linestyle=':', alpha=0.6)
ax.set_xlim(-1, 5)
ax.set_ylim(-1, 4)
ax.set_title(r'Determinant as Alternating Multilinear Form: Volume of Parallelepiped', fontsize=13, pad=12, fontweight='bold', color=USSBlue)
ax.grid(True, linestyle='--', alpha=0.3)
ax.legend(loc='upper left')

plt.tight_layout()
plt.savefig('/mnt/9b846436-0407-4e80-b8af-5417ffbdee8e/ObsidianVault/20_University/USS/Ramos_Actuales/Algebra_Lineal/Apuntes/Libro_Axler/Recursos/axler_chapter_9_figura.png')
print("Figura Axler Cap 9 generada con éxito.")
